"""Configuration constants for the RCMAS system."""

GRID_HEIGHT = 4
GRID_WIDTH = 4
INACCESSIBLE_SECTORS = [5, 6, 9, 10]

NUM_AGENTS = 4

NUM_SECTORS = GRID_HEIGHT * GRID_WIDTH
NUM_TIMESTEPS = NUM_SECTORS // NUM_AGENTS
