"""Configuration constants for the RCMAS system."""

GRID_HEIGHT = 4
GRID_WIDTH = 4
INACCESSIBLE_SECTORS = []

NUM_AGENTS = 2

NUM_SECTORS = GRID_HEIGHT * GRID_WIDTH
NUM_TIMESTEPS = NUM_SECTORS // NUM_AGENTS
